title: AID Internal Website Wiki
description: Documentation for the internal AID website built with Flask.
baseurl: "/aiddb-website"
url: "https://cday960.github.io"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark

search_enabled: true


# Always show the guide collection of pages on the navbar
collections:
  guide:
    output: true
  security:
    output: true

just_the_docs:
  collections:
    guide:
      name: Guide
      nav_fold: true
      nav_sort: manual
    security:
      name: Security
      nav_fold: true
