title: AID Internal Website Wiki
description: Documentation for the internal AID website built with Flask.
baseurl: "/aiddb-website"
url: "https://cday960.github.io"

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

search_enabled: true
